### ISSUE TITLE
Context API

### ISSUE THREAD

**Issue by kdy1** [fnapi/fnapi#6]

**Comment by iheyunfei** [comment]
Have you tried approaches like
```ts
const Session: unique symbol = Symbol();
const Db: unique symbol = Symbol();

class SessionImpl {}

class DbImpl {}

class Context {

  get(token: typeof Session): SessionImpl;
  get(token: typeof Db): DbImpl;
  get(token: any): any {
    if (token === Session) {
      return new SessionImpl
    } else if (token === Db) {
      return new DbImpl
    } else {
      throw new Error()
    }
  }
}

const context = new Context;

const session = context.get(Session);
const db = context.get(Db);
```
[playgrond](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAygUwhAluAXDArmFBHLBGCATwFsAjEAGxgF55yrqAKASgG4AoUSWAEQqYc+QsSY16jSjXbce1AIbJ4SVOACSZAA60A3gF8uC5RBiCtumIePAlKgMLgoCAB6w9xmDADmCKCxQIADWCGCYUCTaCCAAZqrIaGBsmIiJmjrU3N5+AUGh4TCR0XHmFClllllcOf6BIWGYimAkFc0k1jXeMCjx9QX0dAxp6smd3d0ATv5Yk2AwYAgA7gmjVV3eBjAI1BBEvTD9YYMMgmzjEzDTULPziysWmRswWzt7FxNQABaTICv3MAAopNfpN2M8jJsuEYeOBoDBeC53FIAU4wEioPJePC9ul5gxEW4oAA6XIsEZJTiwvgwAAmFCkhPcpLqZw4QA)

Does this achieve the goal you mentioned in https://fnapi.dev/docs/design#the-second-magic-identical-api

**Comment by kdy1** [comment]
It will work, at least in first glance. I'll give it a try, thank you!
